// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: connector-services.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JiraPuller_GetProjects_FullMethodName = "/JiraPuller/GetProjects"
	JiraPuller_GetProject_FullMethodName  = "/JiraPuller/GetProject"
)

// JiraPullerClient is the client API for JiraPuller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JiraPullerClient interface {
	GetProjects(ctx context.Context, in *ProjectsRequest, opts ...grpc.CallOption) (*ProjectsResponse, error)
	GetProject(ctx context.Context, in *Key, opts ...grpc.CallOption) (*ID, error)
}

type jiraPullerClient struct {
	cc grpc.ClientConnInterface
}

func NewJiraPullerClient(cc grpc.ClientConnInterface) JiraPullerClient {
	return &jiraPullerClient{cc}
}

func (c *jiraPullerClient) GetProjects(ctx context.Context, in *ProjectsRequest, opts ...grpc.CallOption) (*ProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectsResponse)
	err := c.cc.Invoke(ctx, JiraPuller_GetProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jiraPullerClient) GetProject(ctx context.Context, in *Key, opts ...grpc.CallOption) (*ID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ID)
	err := c.cc.Invoke(ctx, JiraPuller_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JiraPullerServer is the server API for JiraPuller service.
// All implementations must embed UnimplementedJiraPullerServer
// for forward compatibility.
type JiraPullerServer interface {
	GetProjects(context.Context, *ProjectsRequest) (*ProjectsResponse, error)
	GetProject(context.Context, *Key) (*ID, error)
	mustEmbedUnimplementedJiraPullerServer()
}

// UnimplementedJiraPullerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJiraPullerServer struct{}

func (UnimplementedJiraPullerServer) GetProjects(context.Context, *ProjectsRequest) (*ProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjects not implemented")
}
func (UnimplementedJiraPullerServer) GetProject(context.Context, *Key) (*ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedJiraPullerServer) mustEmbedUnimplementedJiraPullerServer() {}
func (UnimplementedJiraPullerServer) testEmbeddedByValue()                    {}

// UnsafeJiraPullerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JiraPullerServer will
// result in compilation errors.
type UnsafeJiraPullerServer interface {
	mustEmbedUnimplementedJiraPullerServer()
}

func RegisterJiraPullerServer(s grpc.ServiceRegistrar, srv JiraPullerServer) {
	// If the following call pancis, it indicates UnimplementedJiraPullerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JiraPuller_ServiceDesc, srv)
}

func _JiraPuller_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiraPullerServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiraPuller_GetProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiraPullerServer).GetProjects(ctx, req.(*ProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JiraPuller_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JiraPullerServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JiraPuller_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JiraPullerServer).GetProject(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

// JiraPuller_ServiceDesc is the grpc.ServiceDesc for JiraPuller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JiraPuller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JiraPuller",
	HandlerType: (*JiraPullerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProjects",
			Handler:    _JiraPuller_GetProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _JiraPuller_GetProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connector-services.proto",
}
