database:
  user: pguser
  password: pgpwd
  host: db
  port: 5432
  db_name: testdb

service_config:
  address: 127.0.0.1
  port: 8080
  jiraUrl: https://jira.atlassian.com/rest/api/2/
  thread: 5
  issueInOneRequest: 75
  maxTimeSleep: 300ms
  minTimeSleep: 10ms
